### ISSUE TITLE
storage.files parse

### ISSUE THREAD

**Issue by ghost** [tonistiigi/mega#12]
I cant parse storage.files, its bug or my fail ?

**Comment by tonistiigi** [comment]
Can you be more specific? Provide code sample and what error you get?

**Comment by ghost** [comment]
storage.files giving all files but i cant parse. this data looks like array but storage.files.lenght returs undefined, storage.files[0] undefined, storage.files["xx"] undefined, i think its my fail i am new on js.

**Comment by tonistiigi** [comment]
`storage.files` is not an array. Its an object that contains all the files by their node ID. If you need an array use `storage.root` or `storage.mounts`.
