### ISSUE TITLE
get file from direct http://gfs204n006.userstorage.mega.co.nz/dl/xxxx--xxxx from megacrypter api

### ISSUE THREAD

**Issue by smolleyes** [tonistiigi/mega#13]
hi

first thanks for your module, works great with mega.co (normal) links

everything is in the title ?

i have some links from megacrypter i can get userstorage links from their api but how can i use your module after that to get file and downlaod functions ?

thanks a lot 

ps: exemple of megacrypter link...

http://megacrypter.com/!0AP70UHmrBvTv5hPSQqEiBhz6cEibrAutVcSF0gzSI8OK0NxnReWvl-SuuabQJy5PsE7LD1SJ3UP68l_Q6O98G2raDAe7WuXi_dXHJiFk57vlPPM3hvvAGhioBSP1L-TyGqOetgKFRGdy0IWablyuUbX-rrR3ChvCha6LzUXc0I!3cf3b170

**Comment by smolleyes** [comment]
i fixed it

thanks...

**Comment by masterkain** [comment]
care to share more details? thanks!
