### ISSUE TITLE
No way to delete file on mega site, you can only create a file.

### ISSUE THREAD

**Issue by manvir-singh** [tonistiigi/mega#15]
There is no way to delete a file on mega's site. You can only upload/download a file.
Is being able to delete a file going to be added?

**Comment by tonistiigi** [comment]
I'm not sure what you mean by "mega site". This library is not affiliated by official mega.co.nz site in any way.

As far as this library goes file.delete() is already implemented. https://github.com/tonistiigi/mega#filedeletecb
