### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by h2oabreu** [tonistiigi/mega#17]
Hi mate, can you help me or explain me how to do a progress bar or show how many bits already have been downloaded?

Thanks.

**Comment by manvir-singh** [comment]
Take a look at the examples it has a progress bar. https://github.com/tonistiigi/mega/blob/master/example/download.js

Note that the example uses a node js module called "node-progress" which can be found here:
https://github.com/visionmedia/node-progress

**Comment by manvir-singh** [comment]
If that helped can you pls close this issue.
