### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by ddavid67** [tonistiigi/mega#6]
Hi.

With node v0.10.2 :

var mega = require('mega')
var fs = require('fs')

var file = mega.file('mp3 link file');

file.download().pipe(fs.createWriteStream('myfile.mp3'));

The MP3 file is corrupt. I cant listen it.

**Comment by tonistiigi** [comment]
Thanks for reporting but most importantly, please do not use any of my code for anything related to piracy. I'm quite sure you don't have the rights to the file that is included in your code sample. Please remove it (file+link) and avoid doing it in the future.

**Comment by tonistiigi** [comment]
For the bug, it should be fixed now.
