### ISSUE TITLE
Cannot read property 'length' of undefined (storage.js)

### ISSUE THREAD

**Issue by anolek** [tonistiigi/mega#9]
Hi,

I have an exception when sometimes, a request fail in storage.js

Message: Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at Object.exports.d64 (~/node_modules/mega/lib/crypto/index.js:17:24)
    at Storage._createUser (~/node_modules/mega/lib/storage.js:151:22)
    at Request.API.request [as _callback](~/node_modules/mega/lib/api.js:74:5)

I think that we need to throw an error or check if "response.tsid" exists in storage.js at line 151 : 

(storage.js near line 151)
    self.api.request({a: 'us', user: user}, function(err, response) {
// maybe add "if(err) cb(err)" here
      var t = crypto.d64(response.tsid) // here, response.tsid is undefined

Thanks !

**Comment by tonistiigi** [comment]
Fixed. Thanks for reporting.
